name: Build Ladybird

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 git cmake ninja-build clang \
            libgl1-mesa-dev libx11-dev libxext-dev libxrender-dev \
            libxcb1-dev libx11-xcb-dev libxrandr-dev libxfixes-dev \
            libxi-dev libxcomposite-dev libxdamage-dev libxss-dev \
            libxtst-dev libgtk-3-dev libasound2-dev

      - name: Build via ladybird.py
        run: |
          chmod +x ./Meta/ladybird.py
          ./Meta/ladybird.py run

      - name: Archive build output
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: ladybird-binary
          path: Build/*/Ladybird/Ladybird  # Adjust if the binary goes elsewhere
